import React,{useEffect,useState,useRef} from 'react';
import {ZoomIn,ZoomOut,RotateCcw} from 'lucide-react';
import type {Item} from './types';
export default function StructureView({item,role='all',onSelect,zh,compact=false,resetToken=0,sharedViewBox=''}:{item:Item|null;role?:string;onSelect?:(v:any)=>void;zh:boolean;compact?:boolean;resetToken?:number;sharedViewBox?:string}){
 useEffect(()=>{setPick(null)},[resetToken,role]);
 const [svg,setSvg]=useState(''),[data,setData]=useState<any>(null),[zoom,setZoom]=useState(1),[pick,setPick]=useState<any>(null);const ref=useRef<HTMLDivElement>(null);
 useEffect(()=>{let active=true;setPick(null);setZoom(1);if(!item)return;Promise.all([fetch(item.view_svg_url||item.svg_url).then(r=>r.text()),fetch(item.structure_url).then(r=>r.json())]).then(([text,d])=>{if(active){const doc=new DOMParser().parseFromString(text,'image/svg+xml');const root=doc.documentElement;root.querySelectorAll('metadata').forEach(n=>n.remove());root.removeAttribute('width');root.removeAttribute('height');root.setAttribute('preserveAspectRatio','xMidYMid meet');if(sharedViewBox)root.setAttribute('viewBox',sharedViewBox);const bg=root.querySelector('rect');if(bg)bg.setAttribute('fill','transparent');setSvg(new XMLSerializer().serializeToString(root));setData(d)}}).catch(()=>{if(active){setSvg('');setData(null)}});return()=>{active=false}},[item?.structure_url,sharedViewBox]);
 useEffect(()=>{if(!ref.current)return;ref.current.querySelectorAll('path,polyline,ellipse').forEach((el:any)=>{const level=el.dataset.level;const group=el.closest('[data-role]')?.getAttribute('data-role');const r=level||group;const palette:any={backbone:'#244880',flower_anchor:'#b36163',flower_support:'#708166',L1:'#b2864c',L2:'#618f9c',L3:'#936c9b'};if(palette[r])el.style.stroke=palette[r];const cid=el.dataset.curveId;const related=pick?.cid&&(cid===pick.cid||cid===pick.parent||el.dataset.parentCurveId===pick.cid);const flowerMatch=pick?.flowerId&&el.dataset.flowerId===pick.flowerId;const groupMatch=pick&&!pick.cid&&!pick.flowerId&&group===pick.role;el.style.opacity=pick?(related||flowerMatch||groupMatch?'1':'.14'):(role==='all'||r===role?'1':'.13');el.style.cursor='pointer';if(!compact){el.setAttribute('tabindex','0');el.setAttribute('role','button');el.setAttribute('aria-label',`${r} ${el.dataset.curveId?.split('__').pop()||el.dataset.flowerId||''}`)}el.style.transition='opacity .16s';if(el.tagName==='ellipse')el.style.fill='transparent'});},[svg,role,pick,zh]);
 function click(e:React.MouseEvent){const el=(e.target as Element).closest('path,polyline,ellipse') as SVGElement|null;if(!el)return;const group=el.closest('[data-role]')?.getAttribute('data-role')||'';const cid=el.getAttribute('data-curve-id');const curves=data?.selection.selected_candidates.flatMap((u:any)=>u.curves)||[];const c=curves.find((v:any)=>v.curve_id===cid);const parent=c?.parent_curve_id;const role=c?.level||group;if(role==='unit_boundary')return;const flowerId=el.getAttribute('data-flower-id');setPick({cid,parent,role,flowerId});const names:any={backbone:zh?'主藤':'Main vine',flower_anchor:zh?'花位':'Flower site',flower_support:zh?'承花路径':'Flower-support path',L1:zh?'普通父枝':'Parent branch',L2:zh?'子枝':'Child branch',L3:zh?'三级枝':'Third-level branch'};const desc:any={backbone:zh?'主藤贯穿重复单元，构成连续的花藤骨架。':'The main vine continues through adjacent repeats and anchors the floral composition.',flower_anchor:zh?'此花位及其对应的承花路径已高亮；位置范围与连接作用分别记录。':'This flower site and its supporting path are highlighted together. Position and connection are recorded separately.',flower_support:zh?'承花路径连接主藤与花位，属于给定花藤配置。':'This path connects a flower site to the main vine and belongs to the given floral configuration.',L1:zh?`此父枝带有 ${curves.filter((v:any)=>v.parent_curve_id===cid).length} 条子枝。父枝及其子枝作为完整配置参与选择。`:`This parent carries ${curves.filter((v:any)=>v.parent_curve_id===cid).length} child branches. They form a complete candidate configuration.`,L2:zh?'此子枝依附于高亮的父枝，随完整父子枝组共同参与几何检查与选择。':'This child attaches to the highlighted parent. Their complete configuration is checked and selected together.'};if(role==='flower_anchor'&&!data?.flower_mount_plan.mounts.some((m:any)=>m.flower_id===flowerId)){desc[role]=zh?'此花位已高亮。它的位置与主藤的连续走势共同构成这套花藤配置。':'This flower site is highlighted. Its position and the continuous main vine define this floral configuration.'}onSelect?.({label:names[role]||role,description:desc[role]||(zh?'依附于高亮父枝的自定义分枝。':'A custom branch attached to the highlighted parent.')})}
 return <div className={'structure-canvas '+(compact?'compact':'')}><div className="canvas-kicker"><span>{zh?'三周期视图':'THREE-REPEAT VIEW'}</span><div><button aria-label="Zoom out" onClick={()=>setZoom(Math.max(1,zoom-.25))}><ZoomOut size={16}/></button><span>{Math.round(zoom*100)}%</span><button aria-label="Zoom in" onClick={()=>setZoom(Math.min(2.5,zoom+.25))}><ZoomIn size={16}/></button><button aria-label="Reset view" onClick={()=>{setZoom(1);setPick(null);onSelect?.(null)}}><RotateCcw size={14}/></button></div></div><div className="svg-scroll" aria-label={zh?'可横向滚动的结构视图':'Scrollable structure view'}><div className="svg-stage" ref={ref} onClick={click} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();click(e as unknown as React.MouseEvent)}}} style={{width:`${zoom*100}%`}} dangerouslySetInnerHTML={{__html:svg}}/></div><div className="repeat-labels"><span>−1</span><span>{zh?'中央单元':'CENTRAL REPEAT'}</span><span>+1</span></div></div>
}
